# Data Encryption Configuration for mobile-api

encryption:
  # Database encryption settings
  database:
    enabled: true
    algorithm: AES256
    key_rotation: true
    at_rest:
      enabled: true
    in_transit:
      enabled: true
      tls_version: TLSv1.2

  # Storage encryption settings
  storage:
    enabled: true
    server_side:
      algorithm: AES256
      enabled: true
    client_side:
      enabled: false

  # API encryption settings
  api:
    ssl_enabled: true
    minimum_tls_version: TLSv1.2
    protocols:
      - TLSv1.2
      - TLSv1.3
    cipher_suites:
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES128-GCM-SHA256

  # Key management
  key_management:
    rotation_period_days: 90
