AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Resources:
  SubmitImageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: submitImage/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - AdministratorAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /bootstrap
            Method: GET
      Tags:
        Name: submitImage
        business_unit: agile_devops_pmm
        service_name: open_devops_image_rec
        resource_owner: wmarusiak

Outputs:
  SubmitImageAPI:
    Description: "API Gateway endpoint URL for Prod environment for Submit Image Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bootstrap"
  SubmitImageFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt SubmitImageFunction.Arn
  SubmitImageFunctionIamRole:
    Description: "Implicit IAM Role created for Submit Image function"
    Value: !GetAtt SubmitImageFunctionRole.Arn
  SubmitImageFunctionName:
    Description: "SubmitImage function name"
    Value: !Ref SubmitImageFunction
    Export:
      Name: SubmitImageFunctionName

deployments:
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzY5ZjIyOGYzLTFhZjUtNDMxZi1iMWUwLWFiNGZlNzI2MWRmMS82NWUzZGY5YS01YjlhLTExZWYtOWRlYS0xMjAxZjE2ZWQ0MWY=
