name: deploy-submit-image-test-staging
on:
  push:
    branches:
      - '*'
      - '!mainline'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd ${{ github.workspace }}/submitImage
          ls
          go test ./opendevopslambda...

  deploy-us-west-1:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Deploy us-west-1
        run: echo "Deploy us-west-1"

  integration-test-us-west-1:
    runs-on: ubuntu-latest
    needs: deploy-us-west-1
    steps:
      - name: Integration test us-west-1
        run: echo "Integration test us-west-1"

  deploy-us-east-2:
    runs-on: ubuntu-latest
    needs: integration-test-us-west-1
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Deploy us-east-2
        run: echo "Deploy us-east-2"

  integration-test-us-east-2:
    runs-on: ubuntu-latest
    needs: deploy-us-east-2
    steps:
      - name: Integration test us-east-2
        run: echo "Integration test us-east-2"
