name: deploy-submit-image-test-staging
on:
  push:
    branches:
      - '*'
      - '!mainline'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: echo "Run unit tests"

  deploy-us-west-1:
    runs-on: ubuntu-latest
    environment: stg-us-west
    needs: run-unit-tests
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ secrets.WMARUSIAK_PAT_MACOS_LAPTOP_2025 }}'
          environment: stg-us-west

      - name: Deploy us-west-1
        run: echo "Deploy us-west-1"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ secrets.WMARUSIAK_PAT_MACOS_LAPTOP_2025 }}'
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ secrets.WMARUSIAK_PAT_MACOS_LAPTOP_2025 }}'
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

  integration-test-us-west-1:
    runs-on: ubuntu-latest
    needs: deploy-us-west-1
    steps:
      - name: Integration test us-west-1
        run: echo "Integration test us-west-1"

  deploy-us-east-2:
    runs-on: ubuntu-latest
    environment: stg-us-east
    needs: integration-test-us-west-1
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Deploy us-east-2
        run: echo "Deploy us-east-2"

  integration-test-us-east-2:
    runs-on: ubuntu-latest
    needs: deploy-us-east-2
    steps:
      - name: Integration test us-east-2
        run: echo "Integration test us-east-2"
